name: smart-parking-lot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - pip:
    - customtkinter>=5.2.0
    - CTkMessagebox>=2.5
    - pyserial>=3.5
    - pywinstyles>=1.0.0
    - Pillow>=10.0.0

